FROM node:14.16.1-alpine

WORKDIR /app

ENV PATH /app/node_modules/.bin:$PATH

COPY package.json ./
COPY yarn.lock ./
RUN yarn install --production

COPY . ./

RUN yarn build

# Use below nginx version
FROM nginx:1.15.2-alpine as production
ENV NODE_ENV production

# Copy the build folder of the react app
COPY ./public /var/www
# Copy the ngnix configrations
COPY nginx.conf /etc/nginx/nginx.conf
# Expose it on port 80
EXPOSE 80
ENTRYPOINT ["nginx","-g","daemon off;"]